# Generated by Django 5.1.1 on 2025-02-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Digital Wallet')], default='cash', max_length=20),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
